# Generated by Django 5.1.5 on 2025-03-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='City Name')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
    ]
